name: ParkyTeamsLatest
version: '1.2-BETA'
main: org.ProunceDev.parkyTeamsLatest.ParkyTeamsLatest
softdepend: [PlaceholderAPI]
api-version: '1.21'
commands:
  team:
    description: Allows you to create, invite, kick, and disband teams.
    usage: /team <create | invite | kick | disband> <team name | player>
  team_death_tracker:
    description: Admin command for resetting player death flags.
    usage: /team_death_tracker <resetall | reset <player>>
    permission: parkyteamslatest.manage
    permission-message: You don't have permission to run this command.